baseurl = "http://kodsnack.se"
languageCode = "sv"
title = "Kodsnack"
pluralizeListTitles = false

[params]
Description = "Podcast om kod, för kodare. På svenska."
CopyrightHTML = "<a href=\"https://github.com/kodsnack\">github.com/kodsnack</a>"

[permalinks]
avsnitt = "/:slug/"

[[menu.main]]
        name = "Om"
        url = "/om/"
        weight = -200

[[menu.main]]
        name = "Avsnitt"
        url = "/avsnitt/"
        weight = -199

[[menu.main]]
        name = "Framträdanden"
        url = "/events/"
        weight = -198

[[menu.main]]
        name = "Video"
        url = "/video/"
        weight = -197

[[menu.main]]
        name = "Sumpsnack (bonusmaterial)"
        url = "/sumpsnack/"
        weight = -196

[[menu.main]]
        name = "Prenumerera (RSS)"
        url = "http://feedpress.me/kodsnack"
        weight = -195

[[menu.main]]
        name = "Prenumerera (iTunes)"
        url = "http://itunes.apple.com/se/podcast/kodsnack/id561631498?l=en"
        weight = -194

[[menu.main]]
        name = "@kodsnack"
        url = "https://twitter.com/KodSnack"
        weight = -193

