BaseURL = "https://kodsnack.se"
languageCode = "sv"
title = "Kodsnack - podd av kodare, fÃ¶r kodare, pÃ¥ svenska"
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
Description = "Podcast om kod, fÃ¶r kodare. PÃ¥ svenska."
CopyrightHTML = "<a href=\"https://github.com/kodsnack\">github.com/kodsnack</a>"

[permalinks]
avsnitt = "/:slug/"

[taxonomies]
  category = "categories"
  people = "people"
  tag = "tags"
  sponsor = "sponsor"

[[menu.main]]
        name = "Om"
        url = "/om/"
        weight = -200

[[menu.main]]
        name = "Avsnitt"
        url = "/avsnitt/"
        weight = -199

[[menu.main]]
        name = "ðŸ›’ Handla"
        url = "https://shop.spreadshirt.se/kodsnack/"
        weight = -198

[[menu.main]]
        name = "Slack"
        url = "https://join.slack.com/t/podsnack/shared_invite/zt-wh2ussm9-xFOqpvjgF16G2eDhaBy1hw"
        weight = -197

[[menu.main]]
        name = "Sponsra"
        url = "/sponsra/"
        weight = -196

[[menu.main]]
        name = "Kod"
        url = "/code/"
        weight = -195

[[menu.main]]
        name = "FramtrÃ¤danden"
        url = "/events/"
        weight = -194

[[menu.main]]
        name = "ðŸ‡¬ðŸ‡§ English feed"
        url = "/international/"
        weight = -193

[[menu.main]]
        name = "Video"
        url = "/video/"
        weight = -192

[[menu.main]]
        name = "Sumpsnack (bonusmaterial)"
        url = "/sumpsnack/"
        weight = -191

[[menu.main]]
        name = "Prenumerera (RSS)"
        url = "https://feeds.kodsnack.se"
        weight = -190

[[menu.main]]
        name = "Prenumerera (iTunes)"
        url = "https://itunes.apple.com/se/podcast/kodsnack/id561631498?l=en"
        weight = -189

[[menu.main]]
        name = "Prenumerera (Overcast)"
        url = "https://overcast.fm/itunes561631498/kodsnack"
        weight = -188

[[menu.main]]
        name = "Prenumerera (Pocket casts)"
        url = "http://pca.st/h7lO"
        weight = -187

[[menu.main]]
        name = "ðŸ¦£ @kodsnack"
        url = "https://social.podsnack.se/@kodsnack"
        weight = -186
[[menu.main]]
        name = "ðŸ“¼ Youtube"
        url = "https://www.youtube.com/channel/UCyF3GrbgMV5THKZF4lpcQpg/videos?view=57"
        weight = -185
[[menu.main]]
        name = "Att vara gÃ¤st"
        url = "/guest/"
        weight = -184